name: Documentation

on:
  pull_request:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install ".[dev,docs]"
    - name: Generate Docs
      run: |
        make -C docs html
        touch docs/_build/html/.nojekyll
    - name: Publish Docs
      if: github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/_build/html/ # The folder the action should deploy.